name: Increment Version
on:
  push:
    branches: [master]
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: christian-draeger/increment-semantic-version@1.1.0
        with:
          current-version: '1.0.0'
          version-fragment: 'patch'
